version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: finbase-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  collector:
    build: .
    container_name: finbase-collector-yfinance
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    stop_grace_period: 30s
